import htmlminInstance from 'gulp-htmlmin';

function htmlmin() {
  return htmlminInstance({
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    removeComments: true,
  });
}

export default htmlmin;
