import { packageData, isProd } from './app.js';
import { pathSrc } from './path.js';
import getTwigGlobals from './twig.js';

// DEL
const del = {
  force: true,
};

// HTML
const twig = {
  base: pathSrc,
  data: getTwigGlobals(),
};
const htmlmin = {
  collapseWhitespace: true,
  includeAutoGeneratedTags: false,
  minifyCSS: true,
  minifyJS: true,
  removeComments: true,
};
const versionNumber = {
  value: packageData.version || '%MDS%',
  append: {
    key: 'v',
    to: 'all',
  },
};

// IMAGE
const imagemin = {
  gifsicle: {
    optimizationLevel: 1,
    interlaced: false,
  },
  optipng: {
    optimizationLevel: 5,
  },
  mozjpeg: {
    quality: 75, progressive: true,
  },
  pngquant: {
    quality: [0.7, 0.9],
    speed: 7,
  },
  svgo: {
    plugins: [
      {
        name: 'removeViewBox',
        active: false,
      },
      {
        name: 'convertShapeToPath',
        active: false,
      },
      {
        name: 'convertEllipseToCircle',
        active: false,
      },
    ],
  },
};

// CSS
const sass = {
  api: 'modern-compiler',
  loadPaths: ['node_modules'],
  silenceDeprecations: ['mixed-decls', 'color-functions', 'global-builtin', 'import'],
};
const autoprefixer = {
  cascade: !isProd,
  grid: false,
};
const cssnano = {
  preset: [
    'default',
    {
      discardComments: {
        removeAll: true,
      },
    },
  ],
};

// JS
const terser = {
  mangle: true,
  keep_classnames: true,
  keep_fnames: false,
  ie8: false,
};

// ALL TOGETHER
const plugin = {
  del,
  twig,
  htmlmin,
  versionNumber,
  imagemin,
  sass,
  autoprefixer,
  cssnano,
  terser,
};

export {
  del,
  twig,
  htmlmin,
  versionNumber,
  imagemin,
  sass,
  autoprefixer,
  cssnano,
  terser,
};

export default plugin;
