import htmlminInstance from 'gulp-htmlmin';

const htmlminConfig = {
  collapseWhitespace: true,
  includeAutoGeneratedTags: false,
  minifyCSS: true,
  minifyJS: true,
  removeComments: true,
};

const htmlmin = htmlminInstance(htmlminConfig);

export default htmlmin;
